### ISSUE TITLE
DTS or rewrite to TS

### ISSUE THREAD

**Issue by Merynek** [haensl/google-optimize-service#66]
Hello,

I use this fantastic library but I use Typescript so it would be great if the library have types :-)

**Comment by haensl** [comment]
Hi,

thank you for the feedback!

I understand that types would be a good addition for Typescript users. Unfortunately I am neither a Typescript user, nor do I have the time on my hands to learn and add Typescript at this time.

Feel free to implement a Typescript version and submit a PR 👍
